jenkins:
  systemMessage: "Jenkins configured as code"

jobs:
  - script: >
      pipelineJob('devops-as-code-ci-demo') {
          definition {
              cpsScm {
                  scm {
                      git {
                          remote {
                        	credentials('github-credentials')
                        	url('https://github.com/xebialabs/devops-as-code-ci-demo.git')
                          }
                      }
                  }
                  scriptPath('Jenkinsfile')
              }
          }
      }
  - script: >
      pipelineJob('devops-as-code-ci-demo-windows') {
          definition {
              cpsScm {
                  scm {
                      git {
                          remote {
                        	credentials('github-credentials')
                        	url('https://github.com/xebialabs/devops-as-code-ci-demo.git')
                          }
                      }
                  }
                  scriptPath('Jenkinsfile-windows')
              }
          }
      }
  - script: >
      pipelineJob('devops-as-code-eks-blueprint') {
          definition {
              cpsScm {
                  scm {
                      git {
                          remote {
                        	credentials('github-credentials')
                        	url('https://github.com/xebialabs/e-commerce-microservice.git')
                          }
                      }
                  }
                  scriptPath('store/Jenkinsfile')
              }
          }
      }

credentials:
  system:
    domainCredentials:
      - credentials:
        - usernamePassword:
            scope:    GLOBAL
            id:       github-credentials
            username: ${GITHUB_USER}
            password: ${GITHUB_TOKEN}
        - usernamePassword:
            scope:    GLOBAL
            id:       xld-credentials
            username: admin
            password: admin
        - usernamePassword:
            scope:    GLOBAL
            id:       xlr-credentials
            username: admin
            password: admin
