apiVersion: xl-deploy/v1beta1
kind: Infrastructure
spec:
- name: local-docker
  type: docker.Engine
  dockerHost: http://dockerproxy:2375
---
apiVersion: xl-release/v1beta1
kind: Configurations
spec:
- name: XL Deploy
  type: xldeploy.XLDeployServer
  url: http://localhost:4516
  username: admin
  password: hatseflats
- name: SonarQube
  type: sonar.Server
  url: http://url:9001
  username: admin
  password: admin
